[package]
name = "dicepass"
version = "0.1.0"
authors = ["iwburns <iburns@quantumedgetechnology.com>"]

[dependencies]
lib_dicepass_gen = { git = "https://github.com/iwburns/lib_dicepass_gen" }

[dependencies.clap]
version = "~2.30.0"
default-features = false
